Use Python3-compatible code when wrapping setup.py
I tried to install the docutils sdist

https://wheels.galaxyproject.org/packages/docutils-0.12.tar.gz#md5=3aabc9b5d4a76ec20a0fa597910e2480

in a Python3 virtualenv, but if failed with:
```
Collecting docutils==0.12 (from -r requirements.txt (line 20))
  Downloading https://wheels.galaxyproject.org/packages/docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 5.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g9quytxj/docutils/setup.py", line 3, in <module>
        execfile('setup_wrapped.py')
    NameError: name 'execfile' is not defined
```

Therefore the sdist for the 11 Python packages using `insert_setuptools` in
`wheels/build/wheels.yml` need to be recreated to be Python3-compatible.